name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Release to GitHub
        uses: cycjimmy/semantic-release-action@v4
        with:
            semantic_version: 15.13.28
            branch: main
        
            extra_plugins: |
                @semantic-release/changelog@6.0.0
                @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}