name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

   

      - name: Release to GitHub
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}